task: "rotated_memory_z"
parameters:
  distance: 3
  rounds: 4
  errors:
    after_clifford_depolarization: 0.0
    before_round_data_depolarization: 0.0
    before_measure_flip_probability: 0.0
    after_reset_flip_probability: 0.0
  sampling:
    seed: Null
    shots: 3
    console_log: True
  mapping:
    console_log: True
exports:
  figure:
    exporting: True
    trans_bg: True
    type:
    file: "output/trans_new_test_fig.svg"
  circuit:
    exporting: False
    file: "output/test_circ.txt"
  output:
    file: "output/output.json"
    prettify: True
  pdf_report:
    exporting: False
    file: "examples/example_report.pdf"
