distance: 3
rounds: 2
shots: 5
seed: 42
code_type: rotated_memory_z

after_clifford_depolarization: 0.0
before_round_data_depolarization: 0.0
before_measure_flip_probability: 0.0
after_reset_flip_probability: 0.0
